language: cpp
compiler: gcc

before_install:
  - sudo apt-get install -qq xorg-dev libglu1-mesa-dev libxi-dev libxrandr-dev
  - sudo apt-get install -qq x11proto-xf86vidmode-dev

install: true

before_script:
  - mkdir build
  - cd build
  - cmake -DFENSTERCHEN_TESTS=TRUE ..
  - make -j2

script:
  - make test
